# Generated by Django 3.0.6 on 2020-05-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200527_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
