# Generated by Django 3.0.6 on 2020-05-31 11:10

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='picture',
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='board/images'),
            preserve_default=False,
        ),
    ]
